### ISSUE TITLE
Implement the CS3APIs connector

### ISSUE THREAD

**Issue by diocas** [sciencemesh/cs3api4lab#1]
In order to have a working implementation of CS3APIs for Jupyterlab, the following tasks need to be completed:

- [x] 1. Write a Python client for the CS3APIs with the basic methods required by Jupyter #2 
- [ ] 2. Create a Jupyter Contents Manager that uses the client developed in 1. #2 
- [ ] 3. Create a Jupyter Server Extension to provide the remaining CS3APIs functionality, like Sharing (possibility to share and to retrieve/open what was shared with the user). #3
- [ ] 5. Implement the Jupyter Checkpoints #5 
- [ ] 4. Create a Jupyterlab Extension that gives a web UI for accessing the functionality implemented in 3. #4

## Resources

- Reva: https://github.com/cs3org/reva
- Wopiserver CS3APIs client implementation (can be used as an example implementation): https://github.com/cs3org/wopiserver
- Jupyter Contents API documentation: https://jupyter-notebook.readthedocs.io/en/stable/extending/contents.html
- Jupyterlab Extensions documentation: https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html

**Comment by JarCz** [comment]
CS3 connector in WopiServer implements basic access method:

File operations:
* readFile
* writeFile
* renameFile
* removeFile

File attribuite:
* stat
* statX
* setAttr
* getAttr
* removeAttr

We probably don't need extra file access methods for Jupyter Lab.

@diocas do you have another opinion?

**Comment by diocas** [comment]
@JarCz for files, probably no, but we need to list files in directories and we need everything that is related to share (create share, list shares, etc).

**Comment by JarCz** [comment]
One way is to use API from https://cs3org.github.io/cs3apis/#cs3.sharing.collaboration.v1beta1.CollaborationAPI

and create methods like from reva-client:
* share-create
* share-list
* share-list-received
* share-remove
* share-update
* share-update-received

@labkode is it ok ?

**Comment by diocas** [comment]
Yes, the idea is to have a reva-client implementation in python that we can use.

For now only focus on the issue #2, which corresponds to the task "Create a Jupyter Contents Manager". This depends on having the CS3 client, but just build the client in parallel.
Let's continue the discussion in #2.
