### ISSUE TITLE
Issues found with CERNBox deployment

### ISSUE THREAD

**Issue by diocas** [sciencemesh/cs3api4lab#85]
This ticket is to more freely keep track of issue I'm seeing when testing with CERNBox

- [ ] Cannot expose full EOS namespace to users (#82 )
- [x] The list of shares gives me id's and not the shares names (#95)
- [x] I'm unable to create ~~or open~~ or save files + unable to create folders
- [x] Everything keeps loading from the backend.. Seems too many calls (#96)
- [ ] The info panel has a tab for sharing (as in the designs), but does nothing. Opening the share dialog opens a completely different modal.
- [ ] Searching for users is not working either (backend also replies with `UNIMPLEMENTED`)
    - Update: the backend replies correctly, but the front end shows nothing
- [ ] OCM is still not disabled (AFAIR) and this crashes retrieving the shares. We should be able to disable but, even if enabled, it should still show the local shares
- [x] The extension is reporting `0 hidden files` but I know I have some, so smth's wrong
- [ ] In the Launcher (and maybe why some of the actions fail), the path is `cs3drive:Folder1/Folder2`. This was reported in #99 for shares, but needs to be a general thing
- [x] In the info panel, the size is only reported only in bytes but this is not user friendly
- [ ] "Share file" should be renamed "Public link" and have the same UI as the normal share (we will have to add extra functionality but can do that later). I don't understand what "links is"
- [ ] The context menu of a file is missing the links to create a "share" and "public link". The 3 links should open the same modal, in the corresponding tab.
- [x] Rename "CS3 info" to "File info" in the context menu
- [x] When I tried opening a file called "config" I got the error "t.content.filter is not a function"

As a side note, the experience is a really sluggish compared to the EOS FUSEX mount... Not sure if we need to optimize our extension or REVA...

**Comment by diocas** [comment]
Error when locking:
```log
Feb 02 21:59:44 swan-diogo.cern.ch 1ca6e822e0f6[10408]:       File "/usr/local/lib/python3.9/site-packages/cs3api4lab/api/lock_manager.py", line 54, in is_lock_mine
Feb 02 21:59:44 swan-diogo.cern.ch 1ca6e822e0f6[10408]:         return lock['username'] == user.username and lock['idp'] == user.id.idp and lock['opaque_id'] == user.id.opaque_id
Feb 02 21:59:44 swan-diogo.cern.ch 1ca6e822e0f6[10408]:     TypeError: 'int' object is not subscriptable
```

**Comment by dagl** [comment]
> Error when locking (ping @dagl):
> 
> ```
> Feb 02 21:59:44 swan-diogo.cern.ch 1ca6e822e0f6[10408]:       File "/usr/local/lib/python3.9/site-packages/cs3api4lab/api/lock_manager.py", line 54, in is_lock_mine
> Feb 02 21:59:44 swan-diogo.cern.ch 1ca6e822e0f6[10408]:         return lock['username'] == user.username and lock['idp'] == user.id.idp and lock['opaque_id'] == user.id.opaque_id
> Feb 02 21:59:44 swan-diogo.cern.ch 1ca6e822e0f6[10408]:     TypeError: 'int' object is not subscriptable
> ```

@diocas Could you provide details as to how to replicate this? I was unable to do so.

**Comment by diocas** [comment]
@dagl this happened every time I opened a notebook (which calls the lock). If you cannot replicate, this got solved? I'll try again and will update here if I still see it.

**Comment by dagl** [comment]
@diocas so did this happen again?

**Comment by diocas** [comment]
Now I see this:
```log
  HTTPServerRequest(protocol='https', host='swan-diogo.cern.ch', method='GET', uri='/user/dalvesde/api/contents/Untitled.ipynb?content=1&type=notebook&1649431810487', version='HTTP/1.1', remote_ip='194.12.161.77')
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
      result = await result
    File "/usr/local/lib/python3.9/site-packages/tornado/gen.py", line 234, in wrapper
      yielded = ctx_run(next, result)
    File "/usr/local/lib/python3.9/site-packages/notebook/services/contents/handlers.py", line 111, in get
      model = yield maybe_future(self.contents_manager.get(
    File "/usr/local/lib/python3.9/site-packages/cs3api4lab/api/cs3apismanager.py", line 98, in get
      model = self._notebook_model(path, content=content)
    File "/usr/local/lib/python3.9/site-packages/cs3api4lab/api/cs3apismanager.py", line 301, in _notebook_model
      file_content = self._read_file(tmp_model.path)
    File "/usr/local/lib/python3.9/site-packages/cs3api4lab/api/cs3apismanager.py", line 257, in _read_file
      for chunk in self.file_api.read_file(path, self.cs3_config['endpoint']):
    File "/usr/local/lib/python3.9/site-packages/cs3api4lab/api/cs3_file_api.py", line 96, in read_file
      self.lock_manager.handle_locks(file_path, endpoint) #this will refresh the lock on every file chunk read
    File "/usr/local/lib/python3.9/site-packages/cs3api4lab/api/lock_manager.py", line 89, in handle_locks
      lock = self._get_lock(file_path, endpoint)
    File "/usr/local/lib/python3.9/site-packages/cs3api4lab/api/lock_manager.py", line 113, in _get_lock
      return json.loads(urllib.parse.unquote(list(metadata.values())[0]))
    File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
      return _default_decoder.decode(s)
    File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
      obj, end = self.scan_once(s, idx)
  json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

**Comment by diocas** [comment]
The issues mentioned here were almost all fixed. I'll follow up with individual ones.
